skeleton is ready
js-tasks-ru/htmlcss-20230124_kira-ismailova pull request #9
Opened 2023-02-20 17:41 UTC by KiraIsmailova

skeleton is ready

2023-02-20 17:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-21 10:21 UTC, GSemikozov requested changes

2023-02-21 10:21 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
ширину в модификаторах лучше задавать в процентах

2023-02-21 13:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-21 13:32 UTC, KiraIsmailova commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
ширина в процентах теперь задана во всех элементах

2023-02-21 13:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-21 16:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-21 16:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-22 11:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-22 11:18 UTC, GSemikozov approved these changes

2023-02-22 11:18 UTC, merged